### ISSUE TITLE
Remove weak cyphers from the APACHE config

### ISSUE THREAD

**Issue by trsau** [ausaccessfed/shibboleth-idp-installer#212]
Remove TLS_RSA_WITH_3DES_EDE_CBC_SHA (0xa)  cypher identified as weak by SSLLABs. Add !3DES to the list.

Preferably do same as Hosted IdP, but it currently has three cyphers that are considered weak!

**Comment by smangelsdorf** [comment]
Rather than fiddling with ciphers, the cipher suite should be updated to the latest "intermediate compatibility" recommendations from here:

https://wiki.mozilla.org/Security/Server_Side_TLS

Though I note that 3DES is still included in this list for compatibility with very old browsers (which is a requirement for IdPs, I would expect). The presence of `SSLHonorCipherOrder` means that the server's cipher suite ordering takes precedence over the client's, which means 3DES is only used as a last resort when other ciphers are unsupported.

**Comment by trsau** [comment]
Closed by: Updated cypher list and added documentation to the config file #214
